---
title: "A review of Cell Counting Tool (CCT)"

date: 2018-09-25T12:30:55
lastmod: 2018-09-25T12:30:55
draft: false

authors:
    - Michael Burch

tags:
    - CCT
    - cell counting
    - report

publications:
    - cctv1.4
---

Counting
---------------

The CCT is a powerful windows-based software tool developed to record and process algal cell count data while it is being generated manually by a microscope technician.

The input fields can be customised for samples from any site. The user can select the types and species composition from a predetermined list, which includes data for a comprehensive range of phytoplankton and includes all algal classes and cyanobacteria.

Counting options include the user’s preferences of full field of view, transects, at the chosen magnification. The user is able to easily construct a list of types seen in the sample from a stored list which includes links to web-based photomicroscopy images to aid with identification.

In addition, the user can choose to count and record data for a range of units including single cells, filaments (trichomes) or the area for colonial types such as Microcystis. This accommodates the complexity of how to count and quantify colonial species and genera of cyanobacteria in particular.

The software library already includes the approximate geometric shapes for all types of cells which can then be used to automatically calculate and record biovolume for each species counted.

It is also possible to record and hyperlink photos taken of species and cell types from the user’s individual sample being counted for later checking and also for including in reporting.

The software includes the ability to record the map coordinates of the sample site and later to include a map of the sites in a report. The geolocation information is established in the database for each new site (need to include the source of data used for mapping and constructing image maps)


Reporting
------------------

The real power of the software is in the automatic generation of results which allows for production of customised reports. This is an impressive and time-saving feature.

The full data set is collated resides in a database within C#. This is able to be accessed by reporting routines (in R-script) which allow the user to automatically generate a comprehensive report with just simple commands. The reports are fully professionally formatted and includes graphic and tabular representation of the algal count information for all samples customised for dates and locations for the project.


Comment
----------------

This program is the most sophisticated recording and reporting software that I have encountered and will be very valuable for algal analysis.
