# SITE SETUP
# Documentation: https://sourcethemes.com/academic/

# Color theme.
#   Choose from `default`, `ocean`, `forest`, `dark`, `apogee`, `1950s`, `coffee`, `cupcake`.
color_theme = "default"
# Enable users to switch between day and night mode?
day_night = true

# Font style.
#   Choose from `default`, `classic`, or `playfair`.
font = "default"

# Description for social sharing and search engines. If undefined, superuser role is used in place.
description = "Peasonal website of Ming Su; 苏命的个人网站"

# Default image for social sharing and search engines. Place image in `static/img/` folder and specify image name here.
sharing_image = ""

# Twitter username (without @). Used when a vistor shares your site on Twitter.
twitter = "msu86"

# Diplay a logo in navigation bar rather than title (optional).
#   To enable, place an image in `static/img/` and reference its filename below. To disable, set the value to "".
# logo = "logo.png"
logo = "icon-192.png"

copyright = "&copy; [Ming Su](/) 2014 -2019"
# copyright = "&copy; 2012 - 2019 Dongdong Tian"
# footer = "&copy; Ming Su 2014 -2019"

# Date and time format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
#   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
# date_format = "Jan 2, 2006"
#   Examples: "3:04 pm" or "15:04"
time_format = "3:04 PM"

# Show estimated reading time for posts?
reading_time = true

# Display comment count? Requires commenting to be enabled.
comment_count = true

# Display next/previous section pager?
section_pager = true

# Enable global LaTeX math rendering?
#   If false, you can enable it locally on a per page basis.
math = false

# Enable global source code highlighting? true/false
# Documentation: https://sourcethemes.com/academic/docs/writing-markdown-latex/#highlighting-options
highlight = true
highlight_languages = ["r"]  # Add support for highlighting additional languages
# highlight_style = "github"  # For supported styles, see https://cdnjs.com/libraries/highlight.js/

# Enable in-built social sharing buttons?
sharing = true

# Privacy pack
#   Show a cookie consent message to visitors
#   Anonymize IP in Google Analytics (if enabled)
privacy_pack = false

# Get user avatars from Gravatar.com? (true/false)
gravatar = false

  # address = "Building 5 Room 309, Shuangqing Rd. 18, Haidian, Beijing, 100085."
  # office_hours = """Monday to Friday, 08:30 to 17:30<br>
  # or email for appointment"""
  phone = "+86 10 62843038"
  email = "mingsu@rcees.ac.cn"
  skype = "mingsu86"
  telegram = ""
  keybase = "mingsu"  # Your keybase.io username.
  appointment_url = "https://app.acuityscheduling.com/schedule.php?owner=17141571"


  # Discussion link (e.g. link to a forum, mailing list, or chat).
  #   Uncomment line below to use.
# discussion = { name = "Discuss", url = "https://discourse.gohugo.io" }

  # Enable/disable map in Contact widget.
  # To show your address on a map in the contact widget, you need to enter your latitude, longitude and choose
  # a map provider below.
  # To use Google Maps, set `map = 1` and enter your API key that can be obtained here:
  #   https://developers.google.com/maps/documentation/javascript/get-api-key
  # To use OpenStreetMap tiles, set `map = 2`.
  # To use OpenStreetMap on a high traffic site, set `map = 3` and enter your API key that can be obtained here:
  #   https://www.mapbox.com/studio/account/tokens
  # To get your coordinates, right-click on Google Maps and choose "What's here?". The coords will show up at the bottom.
  #
  # Map provider:
  #   0: No map
  #   1: Google Maps
  #   2: OpenStreetMap (Mapnik)
  #   3: OpenStreetMap (Mapbox)
  map = 2
  map_api_key = ""
  latitude = "40.00775"
  longitude = "116.33741"
  zoom = 15

# Publication types.
#   Used to categorize publications.
#   The index of the publication type in the list is used as its unique numerical identifier.
#   The numeric ID is used in a publication's frontmatter to categorize it.
#   The language can be edited below.
#   For multilingual sites, `publication_types` can be copied to each language section at the end of this file and
#   translated.
publication_types = [
    'Uncategorized',  # 0
    'Conference paper',  # 1
    'Journal article',  # 2
    'Manuscript',  # 3
    'Report',  # 4
    'Book',  # 5
    'Book section',  # 6
    'Patent',  # 7
    'Copyright'  # 8
]

# Align the main menu to the right of the page? (true/false)
menu_align_right = false

# Link custom CSS and JS assets
#   (relative to /static/css and /static/js respectively)
custom_css = ['custom.css']
custom_js  =  ["js/fix-toc.js", "js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js", "js/math-code.js", "js/external-link.js", "js/alt-title.js"]

# Configuration of talk pages.
[talks]
  # Show talk time?
  time = true

# Configuration of publication pages.
# [publications]
  # # Date format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
  # #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  # date_format = "January, 2006"

# Configuration of project pages.
[projects]
  # List publications and talks related to the project?
  list_children = true

  # Post list format.
  #   0 = Simple
  #   1 = Detailed
  #   2 = Stream
  post_format = 2

  # Publication list format.
  #   0 = Simple
  #   1 = Detailed
  #   2 = APA
  #   3 = MLA
  #   4 = Stream
  publication_format = 4

  # Talk list format.
  #   0 = Simple
  #   1 = Detailed
  #   2 = Stream
  talk_format = 2

# Search.
[search]
  # Search provider:
  #   0: No search engine
  #   1: Built-in (Fuse)
  #   2: Algolia (https://www.algolia.com)
  engine = 1

  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  [search.algolia]
    app_id = ""
    api_key = ""
    index_name = ""
    show_logo = false
